INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','product_location','2','商城首页','admin',now(),'','CD-CHW000015','CD-CHW000015');

INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','rent_prod_location','2','租赁首页','admin',now(),'','CD-CHW000015','CD-CHW000015');

/*
-- Query: SELECT start_point,end_point,'1' start_weight,'1000' start_price,'1' add_weight,'5' add_price,'admin' updater, now() as update_datetime,'CD-CZH000001' company_code,'CD-CZH000001' system_code FROM tstd_express_rule where start_point='浙江省'
-- Date: 2017-10-17 16:58
*/
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','安徽省','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','北京市','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','福建省','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','甘肃省','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','广东省','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','广西壮族自治区','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','贵州省','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','海南省','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','河北省','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','河南省','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','黑龙江省','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','湖北省','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','湖南省','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','吉林省','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','江苏省','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','江西省','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','辽宁省','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','内蒙古自治区','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','宁夏回族自治区','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','青海省','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','山东省','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','山西省','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','陕西省','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','上海市','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','四川省','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','天津市','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','西藏自治区','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','新疆维吾尔自治区','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','云南省','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','浙江省','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','重庆市','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','香港','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','澳门','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');
INSERT INTO `tstd_express_rule` (`start_point`,`end_point`,`start_weight`,`start_price`,`add_weight`,`add_price`,`updater`,`update_datetime`,`company_code`,`system_code`) VALUES ('浙江省','台湾','1','1000','1','5','admin',now(),'CD-CZH000001','CD-CZH000001');