
DROP TABLE IF EXISTS `tstd_country`;
CREATE TABLE `tstd_country` (
  `inter_code` varchar(32) NOT NULL COMMENT '国际代码',
  `inter_name` varchar(32) DEFAULT NULL COMMENT '国际名称',
  `chinese_name` varchar(32) DEFAULT NULL COMMENT '中文名称',
  `inter_simple_code` varchar(32) DEFAULT NULL COMMENT '国际简码',
  `continent` varchar(32) DEFAULT NULL COMMENT '所属洲际',
  `order_no` int(11) DEFAULT '0' COMMENT '展示顺序',
  `status` varchar(32) DEFAULT '0' COMMENT '状态 0=不启用 1=启用',
  PRIMARY KEY (`inter_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

UPDATE `tsys_dict` SET `dvalue`='基于ETH的token币' WHERE `parent_key`='coin_type' AND `dkey`='1';
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','coin_type','2','基于WAN的token币','admin',now(),'','CD-TOKEN00018','CD-TOKEN00018');

INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('0',NULL,'red_packet_status','红包状态','admin',now(),'','CD-TOKEN00018','CD-TOKEN00018');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','red_packet_status','0','已发布','admin',now(),'','CD-TOKEN00018','CD-TOKEN00018');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','red_packet_status','1','未抢完','admin',now(),'','CD-TOKEN00018','CD-TOKEN00018');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','red_packet_status','2','已抢完','admin',now(),'','CD-TOKEN00018','CD-TOKEN00018');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','red_packet_status','3','部分退回','admin',now(),'','CD-TOKEN00018','CD-TOKEN00018');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','red_packet_status','4','全部退回','admin',now(),'','CD-TOKEN00018','CD-TOKEN00018');

INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('0',NULL,'red_packet_type','红包类型','admin',now(),'','CD-TOKEN00018','CD-TOKEN00018');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','red_packet_type','0','定额红包','admin',now(),'','CD-TOKEN00018','CD-TOKEN00018');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','red_packet_type','1','拼手气红包','admin',now(),'','CD-TOKEN00018','CD-TOKEN00018');

INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','jour_biz_type_user','sendredpacket_in','抢红包','admin',now(),'','CD-TOKEN00018','CD-TOKEN00018');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','jour_biz_type_user','sendredpacket_out','发红包','admin',now(),'','CD-TOKEN00018','CD-TOKEN00018');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','jour_biz_type_user','redpacket_back','红包退回','admin',now(),'','CD-TOKEN00018','CD-TOKEN00018');

INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','jour_biz_type_plat','hb_in','红包转入','admin',now(),'','CD-TOKEN00018','CD-TOKEN00018');
INSERT INTO `tsys_dict` (`type`,`parent_key`,`dkey`,`dvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('1','jour_biz_type_plat','hb_out','红包转出','admin',now(),'','CD-TOKEN00018','CD-TOKEN00018');

INSERT INTO `tsys_config` (`type`,`ckey`,`cvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('hb','invalidDatetime','30','admin',now(),'红包过期时间(分钟)','CD-TOKEN00018','CD-TOKEN00018');
INSERT INTO `tsys_config` (`type`,`ckey`,`cvalue`,`updater`,`update_datetime`,`remark`,`company_code`,`system_code`) VALUES ('hb','downloadAppUrl','https://www.pgyer.com/ZxWz','admin',now(),'红包领取下载地址','CD-TOKEN00018','CD-TOKEN00018');


/*
-- Query: SELECT * FROM dev_tha_std_core.tstd_country
-- Date: 2018-07-05 16:20
*/
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('001','Canada','加拿大','CA','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('001242','Bahamas','巴哈马','BS','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('001246','Barbados','巴巴多斯','BB','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('001264','Anguilla','安圭拉岛','AI','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('001268','Antigua and Barbuda','安提瓜和巴布达','AG','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('001284','Virgin Islands (British)','维尔京群岛(英国)','VG','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('001340','Virgin Islands (U.S.)','维尔京群岛(美国)','VI','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('001345','Cayman Islands','开曼群岛','KY','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('001441','Bermuda','百慕大','BM','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('001473','Grenada','格林纳达','GD','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('001664','Montserrat','蒙特塞拉特','MS','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('001670','Northern Mariana Islands','北马里亚纳群岛','MP','大洋洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('001671','Guam','关岛','GU','大洋洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('001758','Santa Luzia Island','圣卢西亚岛','','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('001767','Dominica','多米尼克国','DM','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('001784','Saint Vincent and the Grenadines','圣文森特和格林纳丁斯','VCT','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('001787','Puerto Rico','波多黎各','PR','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('001809','Turks and Caicos Islands','土克斯及开科斯群岛','TC','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('001849','Dominican Republic','多米尼加共和国','DO','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('001868','Trinidad and Tobago','特立尼达和多巴哥','TT','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('001869','The Federation of Saint Kitts an','圣基茨和尼维斯','KNA','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('001876','Jamaica','牙买加','JM','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0020','Egypt','埃及','EG','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00211','The Republic of South Sudan','南苏丹共和国','SSD','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00212','Morocco','摩洛哥','MA','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00213','Algeria','阿尔及利亚','DZ','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00216','Tunisia','突尼斯','TN','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00218','Libyan Arab Jamahiriya','利比亚','LY','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00220','Gambia',' 冈比亚','GM','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00221','Senegal','塞内加尔','SN','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00222','Mauritania','毛里塔尼亚','MR','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00223','Mali','马里','ML','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00224','Guinea','几内亚','GN','大洋洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00225','Cote D\'Ivoire','Cote D\'Ivoire','CI','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00226','Burkina Faso','布基纳法索','BF','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00227','Niger','尼日尔','NE','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00228','Togo','多哥','TG','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00229','Benin','贝宁','BJ','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00230','Mauritius','毛里求斯','MU','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00231','Liberia','利比里亚','LR','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00232','Sierra Leone','塞拉利昂','SL','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00233','Ghana','加纳','GH','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00234','Nigeria','尼日利亚','NG','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00235','Chad','乍得','TD','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00236','Central African Republic','中非共和国','CF','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00237','Cameroon','喀麦隆','CM','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00238','Cape Verde','佛得角','CV','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00239','Sao Tome and Principe','圣多美和普林西比','STP','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00240','Equatorial Guinea','赤道几内亚','GQ','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00241','Gabon','加蓬','GA','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00242','Congo','刚果','CG','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00243','Congo, The Democratic Republic O','刚果民主共和国','ZR','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00244','Angola','安哥拉','AO','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00245','Guinea-Bissau','几内亚比绍','GW','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00246','British Indian Ocean Territory','英属印度洋领地','IO','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00248','Seychelles','塞舌尔','SC','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00249','Sudan','苏丹','SD','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00250','Rwanda','卢旺达','RW','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00251','Ethiopia','埃塞俄比亚','ET','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00252','Somalia','索马里','SO','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00253','Djibouti','吉布提','DJ','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00254','Kenya','肯尼亚','KE','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00255','Tanzania','坦桑尼亚','TZ','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00256','Uganda','乌干达','UG','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00257','Burundi','布隆迪','BI','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00258','Mozambique','莫桑比克','MZ','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00260','Zambia','赞比亚','ZM','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00261','Madagascar','马达加斯加','MG','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00262','Mayotte','马约特','YT','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00263','Zimbabwe','津巴布韦','ZW','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00264','Namibia','那米比亚','NA','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00265','Malawi','马拉维','MW','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00266','Lesotho','莱索托','LS','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00267','Botswana','博茨瓦纳','BW','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00268','Swaziland','斯威士兰','SZ','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00269','Comoros','科摩罗','KM','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0027','South Africa','南非','ZA','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00291','Eritrea','厄立特里亚国','ER','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00297','Aruba','阿鲁巴','AW','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00298','Faroe Islands','法罗群岛','FO','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0030','Greece','希腊','GR','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0031','Netherlands','荷兰','NL','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0032','Belgium','比利时','BE','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0033','France','法国','FR','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0034','Spain','西班牙','ES','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00350','Gibraltar','直布罗陀','GI','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00351','Portugal','葡萄牙','PT','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00352','Luxembourg','卢森堡','LU','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00353','Ireland','爱尔兰','IE','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00354','Iceland','冰岛','IS','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00355','Albania','阿尔巴尼亚','AL','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00356','Malta','马尔他','MT','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00357','Cyprus','塞浦路斯','CY','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00358','Finland','芬兰','FI','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00359','Bulgaria','保加利亚','BG','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0036','Hungary','匈牙利','HU','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00370','Lithuania','立陶宛','LT','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00371','Latvia','拉脱维亚','LV','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00372','Estonia','爱沙尼亚','EE','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00373','Moldova','摩尔多瓦','MD','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00374','Armenia','亚美尼亚','AM','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00375','Belarus','白俄罗斯','BY','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00376','Andorra','安道尔共和国','AD','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00377','Monaco','摩纳哥','MC','非洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00378','San Marino','圣马力诺共和国','SM','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00380','Ukraine','乌克兰','UA','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00381','Serbia','塞尔维亚共和国','SRB','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00382','Montenegro','黑山共和国','MNE','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00385','Croatia (local name: Hrvatska)','克罗地亚','HR','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00386','Slovenia','斯洛文尼亚','SI','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00387','Bosnia and Herzegovina','波斯尼亚和黑塞哥维那','BA','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00389','The Republic of Macedonia','马其顿','MKD','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0039','Italy','意大利','IT','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0040','Romania','罗马尼亚','RO','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0041','Switzerland','瑞士','CH','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00420','Czech Republic','捷克','CZ','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00421','Slovakia (Slovak Republic)','斯洛伐克（斯洛伐克人的共和国）','SK','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00423','Liechtenstein','列支敦士登','LI','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0043','Austria','奥地利','AT','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0044','United Kingdom','英国','UK','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00441481','','格恩西岛','','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0045','Denmark','丹麦','DK','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0046','Sweden','瑞典','SE','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0047','Norway','挪威','NO','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0048','Poland','波兰','PL','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0049','Germany','德国','DE','欧洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('005','Falkland Islands (Malvinas)','福克兰群岛','FK','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00501','Belize','伯利兹城','BZ','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00502','Guatemala','危地马拉','GT','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00503','El Salvador','萨尔瓦多','SV','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00504','Honduras','洪都拉斯','HN','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00505','Nicaragua','尼加拉瓜','NI','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00506','Costa Rica','哥斯达黎加','CR','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00507','Panama','巴拿马','PA','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00509','Haiti','海地','HT','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0051','Peru','秘鲁','PE','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0052','Mexico','墨西哥','MX','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0053','Cuba','古巴','CU','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0054','Argentina','阿根廷','AR','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0055','Brazil','巴西','BR','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0056','Chile','智利','CL','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0057','Colombia','哥伦比亚','CO','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0058','Venezuela','委内瑞拉','VE','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00590','Guadeloupe','瓜德罗普岛','GP','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00591','Bolivia','玻利维亚','BO','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00592','Guyana','圭亚那','GY','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00593','Ecuador','厄瓜多尔','EC','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00594','French Guiana','法属圭亚那','GF','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00595','Paraguay','巴拉圭','PY','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00596','Martinique','马提尼克岛','MQ','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00597','Suriname','苏里南','SR','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00598','Uruguay','乌拉圭','UY','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00599','Netherlands Antilles','荷兰安的列斯群岛','AN','美洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0060','Malaysia','马来西亚','MY','亚洲',3,'1');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0061','Australia','澳大利亚','AU','大洋洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0062','Indonesia','印度尼西亚','ID','亚洲',2,'1');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0063','Philippines','菲律宾共和国','PH','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0064','New Zealand','新西兰','NZ','大洋洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0065','Singapore','新加坡','SG','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0066','Thailand','泰国','TH','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00670','East Timor','东帝汶','TP','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00672','Antarctica','南极洲','AQ','南极洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('006723','Norfolk Island','诺福克岛','NF','大洋洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00673','Brunei Darussalam','文莱达鲁萨兰国','BN','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00674','Nauru','瑙鲁','NR','大洋洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00675','Papua New Guinea','巴布亚新几内亚','PG','大洋洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00676','Tonga','汤加','TO','大洋洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00677','Solomon Islands','索罗门群岛','SB','大洋洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00678','Vanuatu','瓦努阿图','VU','大洋洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00679','Fiji','斐济','FJ','大洋洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00680','Palau','帛琉','PW','大洋洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00681','Wallis And Futuna Islands','沃利斯和富图纳群岛','WF','大洋洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00682','Cook Islands','库克群岛','CK','大洋洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00684','American Samoa','萨摩亚','AS','大洋洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00685','Samoa','美属萨摩亚','WS','大洋洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00687','New Caledonia','新喀里多尼亚','NC','大洋洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00688','Tuvalu','图瓦卢','TV','大洋洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00689','French Polynesia','法属玻里尼西亚','PF','大洋洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00690','Tokelau','托克劳','TK','大洋洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00691','Micronesia','密克罗尼西亚','FM','大洋洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00692','Marshall Islands','马绍尔群岛','MH','大洋洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('007','Kazakhstan','哈萨克','KZ','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0081','Japan','日本','JP','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0082','South Korea','韩国','KR','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0084','Vietnam','越南','VN','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00850','North Korea','朝鲜','KP','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00852','Hong Kong','香港','HK','亚洲',2,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00853','Macau','澳门地区','MO','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00855','Cambodia','柬埔寨','KH','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00856','Lao People\'s Democratic Republic','老挝','LAO','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0086','China','中国','CN','亚洲',1,'1');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00880','Bangladesh','孟加拉国','BD','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00886','Taiwan','台湾地区','TW','亚洲',3,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0090','Turkey','土耳其','TR','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0091','India','印度','IN','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0092','Pakistan','巴基斯坦','PK','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0093','Afghanistan','阿富汗','AF','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0094','Sri Lanka','斯里兰卡','LK','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0095','Myanmar','缅甸','MM','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00960','Maldives','马尔代夫','MV','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00961','Lebanon','黎巴嫩','LB','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00962','Jordan','约旦','JO','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00963','Syrian Arab Republic','叙利亚','SY','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00964','Iraq','伊拉克','IQ','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00965','Kuwait','科威特','KW','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00966','Saudi Arabia','沙特阿拉伯','SA','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00967','Yemen','也门','YE','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00968','Oman','阿曼','OM','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00970','Palestine','巴勒斯坦','PS','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00971','United Arab Emirates','阿拉伯联合酋长国','AE','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00972','Israel','以色列','IL','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00973','Bahrain','巴林','BH','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00974','Qatar','卡塔尔','QA','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00975','Bhutan','不丹','BT','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00976','Mongolia','外蒙古','MN','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00977','Nepal','尼泊尔','NP','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('0098','Iran (Islamic Republic of)','伊朗（伊斯兰共和国）','IR','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00992','Tajikistan','塔吉克','TJ','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00993','Turkmenistan','土库曼','TM','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00994','Azerbaijan','阿塞拜疆','AZ','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00995','Georgia','格鲁吉亚','GE','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00996','Kyrgyzstan','吉尔吉斯','KG','亚洲',0,'0');
INSERT INTO `tstd_country` (`inter_code`,`inter_name`,`chinese_name`,`inter_simple_code`,`continent`,`order_no`,`status`) VALUES ('00998','Uzbekistan','乌兹别克斯坦','UZ','亚洲',0,'0');

